// DATABASE STORAGE — MongoDB implementation of the Repository Pattern
// This class handles all CRUD operations for Records stored in MongoDB.
// It's one of two storage "strategies" — the other being FileStorage.
// The StorageFactory decides which one to use based on the user's storage_type.
//
// Spring equivalent:
//   @Repository
//   public class RecordMongoRepository {
//       @Autowired private MongoTemplate mongoTemplate;
//       // ... CRUD methods
//   }

const Record = require('../models/Record');
// ▲ The Mongoose model for the "records" collection.
// It has built-in methods: .create(), .findOne(), .find(), .findOneAndUpdate(), etc.
// Spring equivalent: @Autowired RecordRepository recordRepository;

class DatabaseStorage {

  // CREATE — Save a new record to MongoDB
  // Spring equivalent:
  //   public Record save(String userEmail, RecordDTO data) {
  //       Record record = new Record(data.getId(), userEmail, data.getFirstName(), ...);
  //       return recordRepository.save(record);
  //   }
  async create(userEmail, data) {
    try {
      // Insert a new document into the "records" collection
      // Record.create() validates against schema + inserts in one step
      // Spring: recordRepository.save(new Record(...))
      const document = await Record.create({
        recordId: data.id,                   // Our business ID (UUID generated by service layer)
        userEmail: userEmail.toLowerCase(),   // Owner — used for data isolation in ALL queries
        firstName: data.firstName,
        lastName: data.lastName,
        phone: data.phone || null
      });

      // Return only the fields the API consumer needs (hide MongoDB internals like _id, __v)
      // Spring equivalent: returning a DTO instead of the raw entity
      return {
        status: 'SUCCESS',
        data: {
          id: document.recordId,
          firstName: document.firstName,
          lastName: document.lastName,
          phone: document.phone || null
        }
      };
    } catch (error) {
      // MongoDB connection/server errors → generic message (don't leak DB details)
      if (error.name === 'MongoServerError' || error.name === 'MongoError') {
        throw new Error('Storage backend unreachable');
      }
      throw error; // Re-throw everything else (validation bugs, etc.)
    }
  }

  // READ — Find one record by ID (scoped to this user)
  // Spring equivalent:
  //   Optional<Record> findByRecordIdAndUserEmail(String recordId, String email);
  //
  // SECURITY: Always filter by BOTH recordId AND userEmail.
  // Without userEmail filter → any user could read any other user's data (IDOR bug).
  async read(userEmail, id) {
    try {
      // Query: WHERE recordId = id AND userEmail = email
      // Spring: Criteria.where("recordId").is(id).and("userEmail").is(email)
      const document = await Record.findOne({
        recordId: id,
        userEmail: userEmail.toLowerCase()
      });

      // null means: record doesn't exist OR belongs to another user
      // Either way, caller gets null → route handler sends 404
      if (!document) {
        return null;
      }

      return {
        status: 'SUCCESS',
        data: {
          id: document.recordId,
          firstName: document.firstName,
          lastName: document.lastName
        }
      };
    } catch (error) {
      if (error.name === 'MongoServerError' || error.name === 'MongoNetworkError') {
        throw new Error('Storage backend unreachable');
      }
      throw error;
    }
  }

  // READ ALL — Get all records belonging to this user
  // Spring equivalent:
  //   List<Record> findByUserEmail(String email);
  //
  // Returns an array (empty [] if user has no records — never null).
  async readAll(userEmail) {
    try {
      // Query: WHERE userEmail = email (returns ALL matching documents)
      // Spring: recordRepository.findByUserEmail(email)
      const documents = await Record.find({
        userEmail: userEmail.toLowerCase()
      });

      // Transform each MongoDB document into a clean response object
      // Spring equivalent: documents.stream().map(doc -> new RecordDTO(...)).toList()
      return documents.map(doc => ({
        id: doc.recordId,
        firstName: doc.firstName,
        lastName: doc.lastName
      }));
    } catch (error) {
      if (error.name === 'MongoNetworkError') {
        throw new Error('Storage backend unreachable');
      }
      throw error;
    }
  }

  // UPDATE — Modify an existing record (partial update with $set)
  // Spring equivalent:
  //   mongoTemplate.findAndModify(query, update, options, Record.class)
  //
  // $set only changes the fields you specify — other fields stay untouched.
  // This is DIFFERENT from JPA merge() which replaces the entire entity.
  async update(userEmail, id, data) {
    try {
      // findOneAndUpdate does 3 things atomically:
      //   1. Finds the document matching the filter (recordId + userEmail)
      //   2. Applies the $set update (only changes firstName/lastName)
      //   3. Returns the UPDATED document (because of { new: true })
      //
      // Without { new: true }, MongoDB returns the OLD document before the change.
      const document = await Record.findOneAndUpdate(
        { recordId: id, userEmail: userEmail.toLowerCase() },  // WHERE clause
        { $set: { firstName: data.firstName, lastName: data.lastName } },  // SET these fields
        { new: true }  // Return the document AFTER update (not before)
      );

      // null = no document matched → either doesn't exist or belongs to another user
      if (!document) {
        return null;
      }

      return {
        status: 'SUCCESS',
        data: {
          id: document.recordId,
          firstName: document.firstName,
          lastName: document.lastName
        }
      };
    } catch (error) {
      if (error.name === 'MongoNetworkError') {
        throw new Error('Storage backend unreachable');
      }
      throw error;
    }
  }

  // DELETE — Remove a record from MongoDB
  // Spring equivalent:
  //   mongoTemplate.findAndRemove(query, Record.class)
  //
  // userEmail in the filter = you can ONLY delete YOUR OWN records.
  // Trying to delete another user's record → filter doesn't match → returns null → 404.
  async delete(userEmail, id) {
    try {
      // Atomically find + delete in one operation
      // Returns the deleted document (or null if nothing matched)
      const result = await Record.findOneAndDelete({
        recordId: id,
        userEmail: userEmail.toLowerCase()
      });

      if (!result) {
        return null;
      }

      return { status: 'SUCCESS' };
    } catch (error) {
      if (error.name === 'MongoNetworkError') {
        throw new Error('Storage backend unreachable');
      }
      throw error;
    }
  }
}

module.exports = DatabaseStorage;
